version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Build
          command: yarn
      - store_artifacts:
          path: ./coverage
          destination: artifact-file
      - run:
          name: coverage
          command: yarn coverage && cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose    